version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # main文件路径
    main: ./cmd/gentr/main.go
    # 生成文件名
    binary: gentr
    # Windows 自动忽略 arm64 ，mac 忽略 32位
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    # Windows 使用 zip
    format_overrides:
      - goos: windows
        format: zip
    # 压缩包命名格式 e.g. gentr_1.0.0_Linux_x86_64.tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'